### ISSUE TITLE
DolphinPlatformApplication.onShutdownException() is called every time

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#210]
When the JavaFX client is called it always ends in an exception and `DolphinPlatformApplication.onShutdownException()` is called.

Log Server:

```
11:01:39,022 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015951: Admin console listening on http://127.0.0.1:10990
11:01:39,023 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: JBoss EAP 6.4.5.GA (AS 7.5.5.Final-redhat-3) started in 15627ms - Started 696 of 732 services (81 services are lazy, passive or on-demand)
11:01:54,904 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-1) S: updating attribute with id '16S' to new value 'SANDYBROWN' even though its old command value 'null' does not conform to the old value of 'SANDYBROWN'. Client overrules server.
11:01:54,906 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-1) S: updating attribute with id '19S' to new value 'TEST' even though its old command value 'null' does not conform to the old value of 'TEST'. Client overrules server.
11:01:54,907 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-1) S: updating attribute with id '2S' to new value 'a95dd990-84c3-45a7-a657-00940eb1665d' even though its old command value 'null' does not conform to the old value of 'a95dd990-84c3-45a7-a657-00940eb1665d'. Client overrules server.
11:01:54,908 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-1) S: updating attribute with id '3S' to new value 'ca71e82b-4ed1-433e-a33b-6f11d9485d97' even though its old command value 'null' does not conform to the old value of 'ca71e82b-4ed1-433e-a33b-6f11d9485d97'. Client overrules server.
11:02:01,821 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-1) S: updating attribute with id '17S' to new value 'true' even though its old command value 'null' does not conform to the old value of 'true'. Client overrules server.
11:02:02,409 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-1) S: updating attribute with id '33S' to new value 'SANDYBROWN' even though its old command value 'null' does not conform to the old value of 'SANDYBROWN'. Client overrules server.
11:02:02,410 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-1) S: updating attribute with id '2S' to new value '8b572160-bfc3-4ea3-b347-4d64bf9f8c7c' even though its old command value 'a95dd990-84c3-45a7-a657-00940eb1665d' does not conform to the old value of '8b572160-bfc3-4ea3-b347-4d64bf9f8c7c'. Client overrules server.
11:02:02,411 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-1) S: updating attribute with id '3S' to new value '22b7140e-ecc1-47f0-b09e-1f7fd126bd34' even though its old command value 'ca71e82b-4ed1-433e-a33b-6f11d9485d97' does not conform to the old value of '22b7140e-ecc1-47f0-b09e-1f7fd126bd34'. Client overrules server.
11:02:51,821 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-2) S: updating attribute with id '55S' to new value 'SANDYBROWN' even though its old command value 'null' does not conform to the old value of 'SANDYBROWN'. Client overrules server.
11:02:51,822 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-2) S: updating attribute with id '58S' to new value 'TEST' even though its old command value 'null' does not conform to the old value of 'TEST'. Client overrules server.
11:02:51,822 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-2) S: updating attribute with id '41S' to new value '9cecbef1-85ee-49a9-bd8b-a5c8882a7477' even though its old command value 'null' does not conform to the old value of '9cecbef1-85ee-49a9-bd8b-a5c8882a7477'. Client overrules server.
11:02:51,822 WARNING [org.opendolphin.core.server.action.StoreValueChangeAction] (http-localhost/127.0.0.1:9080-2) S: updating attribute with id '42S' to new value 'f2f87d4e-eef5-4ba0-b027-479f038be0f8' even though its old command value 'null' does not conform to the old value of 'f2f87d4e-eef5-4ba0-b027-479f038be0f8'. Client overrules server.
11:02:55,851 WARN  [com.canoo.dolphin.server.context.DolphinContextFilter] (http-localhost/127.0.0.1:9080-2) Can not find requested client for id 8f28a650-6da0-44ad-a7d5-e2b05e289b71
```

Log Client:

```
Jul 12, 2016 11:02:55 AM java_util_logging_Logger$info$1 call
INFO: C:           -> Command: DeletedPresentationModel pmId f2f87d4e-eef5-4ba0-b027-479f038be0f8
Jul 12, 2016 11:02:55 AM org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
SEVERE: onException reached, rethrowing in UI Thread, consider setting ClientConnector.onException
com.canoo.dolphin.util.DolphinRemotingException: Error in remoting layer
       at com.canoo.dolphin.client.impl.DolphinPlatformHttpClientConnector.transmit(DolphinPlatformHttpClientConnector.java:77)
       at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2$_closure10.doCall(ClientConnector.groovy:90)
       at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2$_closure10.doCall(ClientConnector.groovy)
       at org.opendolphin.core.client.comm.ClientConnector.doExceptionSafe(ClientConnector.groovy:162)
       at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2.doCall(ClientConnector.groovy:92)
       at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
       at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
       at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
       at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
       at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
       at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
       at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
Caused by: com.canoo.dolphin.client.DolphinSessionException: Server can not handle Dolphin Client ID
       at com.canoo.dolphin.client.impl.IdBasedResponseHandler.handleResponse(IdBasedResponseHandler.java:36)
       at com.canoo.dolphin.client.impl.IdBasedResponseHandler.handleResponse(IdBasedResponseHandler.java:19)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1035)
       at com.canoo.dolphin.client.impl.DolphinPlatformHttpClientConnector.transmit(DolphinPlatformHttpClientConnector.java:73)
       ... 11 more
 
Exception in thread "JavaFX Application Thread" com.canoo.dolphin.util.DolphinRemotingException: Error in remoting layer
       at com.canoo.dolphin.client.impl.DolphinPlatformHttpClientConnector.transmit(DolphinPlatformHttpClientConnector.java:77)
       at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2$_closure10.doCall(ClientConnector.groovy:90)
       at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2$_closure10.doCall(ClientConnector.groovy)
       at org.opendolphin.core.client.comm.ClientConnector.doExceptionSafe(ClientConnector.groovy:162)
       at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2.doCall(ClientConnector.groovy:92)
       at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
       at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
       at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
       at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
       at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
       at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
       at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
Caused by: com.canoo.dolphin.client.DolphinSessionException: Server can not handle Dolphin Client ID
       at com.canoo.dolphin.client.impl.IdBasedResponseHandler.handleResponse(IdBasedResponseHandler.java:36)
       at com.canoo.dolphin.client.impl.IdBasedResponseHandler.handleResponse(IdBasedResponseHandler.java:19)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1035)
       at com.canoo.dolphin.client.impl.DolphinPlatformHttpClientConnector.transmit(DolphinPlatformHttpClientConnector.java:73)
       ... 11 more
```

**Comment by hendrikebbers** [comment]
We need to implement #213 to solve this issue
