### ISSUE TITLE
Remove bean should not throw Exception if not managed by GC

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#222]
If you remove a bean by using the beanManager and the same bean will be removed by GC later this ends in an exception. I think it would be better to only show a warning in the log in this case.
"GC can not remove bean XYZ since it is not managed anymore"

Current exception:

```
13:12:37,523 SEVERE [org.opendolphin.core.server.ServerConnector] (http-localhost/127.0.0.1:9080-2) S: an error ocurred while processing Command: dolphin_platform_intern_destroyController: org.jboss.weld.exceptions.WeldException: WELD-000049 Unable to invoke [method] @PreDestroy public ch.irix.decos.controller.ErrorDetailController.destroy() on ch.irix.decos.controller.ErrorDetailController@4473409d
       at org.jboss.weld.manager.SimpleInjectionTarget.preDestroy(SimpleInjectionTarget.java:133) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at com.canoo.dolphin.server.javaee.DolphinPlatformContextualLifecycle.destroy(DolphinPlatformContextualLifecycle.java:66) [dolphin-platform-server-javaee-0.8.6.jar:0.8.6]
       at org.apache.deltaspike.core.util.bean.ImmutableBean.destroy(ImmutableBean.java:78) [deltaspike-core-api-1.3.0.jar:1.3.0]
       at com.canoo.dolphin.server.javaee.CdiContainerManager.destroyController(CdiContainerManager.java:97) [dolphin-platform-server-javaee-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.controller.ControllerHandler.destroyController(ControllerHandler.java:116) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.context.DolphinContext.onDestroyController(DolphinContext.java:266) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.context.DolphinContext.access$500(DolphinContext.java:68) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.context.DolphinContext$2$4.handleCommand(DolphinContext.java:184) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at org.opendolphin.core.server.comm.CommandHandler$handleCommand.call(Unknown Source)
       at org.opendolphin.core.server.comm.CommandHandler$handleCommand.call(Unknown Source)
       at org.opendolphin.core.server.ServerConnector.receive(ServerConnector.groovy:63) [dolphin-remoting-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.context.DolphinContext.handle(DolphinContext.java:314) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.context.DolphinContextCommunicationHandler.handle(DolphinContextCommunicationHandler.java:76) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.servlet.DolphinPlatformServlet.doPost(DolphinPlatformServlet.java:39) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at com.canoo.dolphin.server.context.DolphinContextFilter.doFilter(DolphinContextFilter.java:73) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at com.canoo.dolphin.server.servlet.CrossSiteOriginFilter.doFilter(CrossSiteOriginFilter.java:50) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.5.Final-redhat-3.jar:7.5.5.Final-redhat-3]
       at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.5.Final-redhat-3.jar:7.5.5.Final-redhat-3]
       at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.5.Final-redhat-3.jar:7.5.5.Final-redhat-3]
       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
Caused by: java.lang.reflect.InvocationTargetException
       at org.jboss.weld.util.reflection.SecureReflections$13.work(SecureReflections.java:267) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:52) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInvocation(SecureReflectionAccess.java:137) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at org.jboss.weld.util.reflection.SecureReflections.invoke(SecureReflections.java:263) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at org.jboss.weld.introspector.jlr.WeldMethodImpl.invoke(WeldMethodImpl.java:168) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at org.jboss.weld.manager.SimpleInjectionTarget.preDestroy(SimpleInjectionTarget.java:131) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       ... 33 more
Caused by: java.lang.IllegalArgumentException: Can't find reference for ch.irix.decos.model.ErrorItem@42b459d9
       at com.canoo.dolphin.server.impl.gc.GarbageCollector.getInstance(GarbageCollector.java:365) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.impl.gc.GarbageCollector.removeReferenceAndCheckForGC(GarbageCollector.java:222) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.impl.gc.GarbageCollector.onRemovedFromList(GarbageCollector.java:183) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.impl.ServerBeanBuilderImpl$2.listChanged(ServerBeanBuilderImpl.java:83) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.impl.collections.ObservableArrayList.notifyExternalListeners(ObservableArrayList.java:67) [dolphin-platform-core-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.impl.collections.ObservableArrayList.fireListChanged(ObservableArrayList.java:56) [dolphin-platform-core-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.impl.collections.ObservableArrayList.clear(ObservableArrayList.java:190) [dolphin-platform-core-0.8.6.jar:0.8.6]
       at ch.irix.decos.controller.ErrorDetailController.destroy(ErrorDetailController.java:65) [classes:]
       ... 39 more

13:12:37,554 ERROR [com.canoo.dolphin.server.context.DolphinContextCommunicationHandler] (http-localhost/127.0.0.1:9080-2) Can not handle the commands (DolphinContext 9b22b67d-d2f3-417f-859b-86df732c6d11): org.jboss.weld.exceptions.WeldException: WELD-000049 Unable to invoke [method] @PreDestroy public ch.irix.decos.controller.ErrorDetailController.destroy() on ch.irix.decos.controller.ErrorDetailController@4473409d
       at org.jboss.weld.manager.SimpleInjectionTarget.preDestroy(SimpleInjectionTarget.java:133) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at com.canoo.dolphin.server.javaee.DolphinPlatformContextualLifecycle.destroy(DolphinPlatformContextualLifecycle.java:66) [dolphin-platform-server-javaee-0.8.6.jar:0.8.6]
       at org.apache.deltaspike.core.util.bean.ImmutableBean.destroy(ImmutableBean.java:78) [deltaspike-core-api-1.3.0.jar:1.3.0]
       at com.canoo.dolphin.server.javaee.CdiContainerManager.destroyController(CdiContainerManager.java:97) [dolphin-platform-server-javaee-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.controller.ControllerHandler.destroyController(ControllerHandler.java:116) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.context.DolphinContext.onDestroyController(DolphinContext.java:266) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.context.DolphinContext.access$500(DolphinContext.java:68) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.context.DolphinContext$2$4.handleCommand(DolphinContext.java:184) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at org.opendolphin.core.server.comm.CommandHandler$handleCommand.call(Unknown Source)
       at org.opendolphin.core.server.comm.CommandHandler$handleCommand.call(Unknown Source)
       at org.opendolphin.core.server.ServerConnector.receive(ServerConnector.groovy:63) [dolphin-remoting-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.context.DolphinContext.handle(DolphinContext.java:314) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.context.DolphinContextCommunicationHandler.handle(DolphinContextCommunicationHandler.java:76) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.servlet.DolphinPlatformServlet.doPost(DolphinPlatformServlet.java:39) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at com.canoo.dolphin.server.context.DolphinContextFilter.doFilter(DolphinContextFilter.java:73) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at com.canoo.dolphin.server.servlet.CrossSiteOriginFilter.doFilter(CrossSiteOriginFilter.java:50) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.5.Final-redhat-3.jar:7.5.5.Final-redhat-3]
       at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.5.Final-redhat-3.jar:7.5.5.Final-redhat-3]
       at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.5.Final-redhat-3.jar:7.5.5.Final-redhat-3]
       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
       at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.12.Final-redhat-1.jar:7.5.12.Final-redhat-1]
Caused by: java.lang.reflect.InvocationTargetException
       at org.jboss.weld.util.reflection.SecureReflections$13.work(SecureReflections.java:267) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:52) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at org.jboss.weld.util.reflection.SecureReflectionAccess.runAsInvocation(SecureReflectionAccess.java:137) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at org.jboss.weld.util.reflection.SecureReflections.invoke(SecureReflections.java:263) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at org.jboss.weld.introspector.jlr.WeldMethodImpl.invoke(WeldMethodImpl.java:168) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       at org.jboss.weld.manager.SimpleInjectionTarget.preDestroy(SimpleInjectionTarget.java:131) [weld-core-1.1.31.Final-redhat-1.jar:1.1.31.Final-redhat-1]
       ... 33 more
Caused by: java.lang.IllegalArgumentException: Can't find reference for ch.irix.decos.model.ErrorItem@42b459d9
       at com.canoo.dolphin.server.impl.gc.GarbageCollector.getInstance(GarbageCollector.java:365) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.impl.gc.GarbageCollector.removeReferenceAndCheckForGC(GarbageCollector.java:222) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.impl.gc.GarbageCollector.onRemovedFromList(GarbageCollector.java:183) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.server.impl.ServerBeanBuilderImpl$2.listChanged(ServerBeanBuilderImpl.java:83) [dolphin-platform-server-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.impl.collections.ObservableArrayList.notifyExternalListeners(ObservableArrayList.java:67) [dolphin-platform-core-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.impl.collections.ObservableArrayList.fireListChanged(ObservableArrayList.java:56) [dolphin-platform-core-0.8.6.jar:0.8.6]
       at com.canoo.dolphin.impl.collections.ObservableArrayList.clear(ObservableArrayList.java:190) [dolphin-platform-core-0.8.6.jar:0.8.6]
       at ch.irix.decos.controller.ErrorDetailController.destroy(ErrorDetailController.java:65) [classes:]
       ... 39 more
```

**Comment by hendrikebbers** [comment]
@netopyr mmh, maybe I changed my opinion over time :D Today I think that throwing an exception is the way to go (since I want to remove beanManager.remove(...) for the 1.0 version)
