### ISSUE TITLE
AbstractBeanBuilder NPE

### ISSUE THREAD

**Issue by blackdrag** [canoo/dolphin-platform#223]
This is on the client side with 0.86, using the icos setup. The effect is a blocked UI. Besides that this exception should probably not occur and most probably hides the real problem, the javafx client tends to throw exceptions in the UI thread without always catching them. Which can easily result in the UI not responding properly anymore

`[2016-07-27 08:56:30,135] [JavaFX Application Thread] ERROR com.canoo.icos.controlcenter.ApplicationEventHandler - Uncought Exception thrown
java.lang.NullPointerException
	at com.canoo.dolphin.impl.AbstractBeanBuilder$1.onEvent(AbstractBeanBuilder.java:58)
	at com.canoo.dolphin.impl.EventDispatcherImpl.onAddedHandler(EventDispatcherImpl.java:106)
	at com.canoo.dolphin.impl.EventDispatcherImpl.modelStoreChanged(EventDispatcherImpl.java:75)
	at org.opendolphin.core.ModelStoreListenerWrapper.modelStoreChanged(ModelStoreListenerWrapper.java:57)
	at org.opendolphin.core.ModelStore.fireModelStoreChangedEvent(ModelStore.java:344)
	at org.opendolphin.core.ModelStore.add(ModelStore.java:137)
	at org.opendolphin.core.client.ClientModelStore.add(ClientModelStore.java:68)
	at org.opendolphin.core.client.comm.ClientConnector.handle(ClientConnector.groovy:227)
	at org.opendolphin.core.client.comm.ClientConnector$handle$0.callCurrent(Unknown Source)
	at org.opendolphin.core.client.comm.ClientConnector.dispatchHandle(ClientConnector.groovy:156)
	at org.opendolphin.core.client.comm.ClientConnector.processResults(ClientConnector.groovy:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure3$_closure12.doCall(ClientConnector.groovy:99)
	at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure3$_closure12.doCall(ClientConnector.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:420)
	at groovy.lang.Closure.run(Closure.java:507)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by hendrikebbers** [comment]
#224 adds some null checks for better NPE

**Comment by hendrikebbers** [comment]
@blackdrag normally an exception that happened in the platform thread should not lock the UI. I added some NPE checks for the given stack trace but need more information for the general problem to have a look at it.

**Comment by blackdrag** [comment]
ok, with the help of Andres I found that the UI was not blocked, just one button, and that this one was blocked on purpose, just the recovery was missing. Sorry for the false alarm
