### ISSUE TITLE
Groovy src always compile against Java 8

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#256]
All sources under src/main/groovy will by compiled by Java 8. Since the server supports Java 7 this will end in java.lang.UnsupportedClassVersionError:

Caused by: java.lang.UnsupportedClassVersionError: org/opendolphin/core/server/ServerDolphin : Unsupported major.minor version 52.0 (unable to load class org.opendolphin.core.server.ServerDolphin)
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2948)
        at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1208)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1688)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1569)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
        at java.lang.Class.getDeclaredMethods(Class.java:1868)
        at org.springframework.core.type.StandardAnnotationMetadata.ge

**Comment by hendrikebbers** [comment]
Andres fixed it
