### ISSUE TITLE
Exception on application startup

### ISSUE THREAD

**Issue by madmas** [canoo/dolphin-platform#275]
Hi

Dolphin Platform  0.8.8

when starting the application generated with the dolphin platform spring boot lazybones template, the server throws the following exception:

```
2016-11-15 21:07:44.960  WARN 57242 --- [ost-startStop-1] org.reflections.Reflections              : could not create Vfs.Dir from url. ignoring the exception and continuing

org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/Users/markus/tmp/lzbtmpl/nov15/server/build/resources/main]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:109) ~[reflections-0.9.10.jar:na]
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91) ~[reflections-0.9.10.jar:na]
	at org.reflections.Reflections.scan(Reflections.java:237) [reflections-0.9.10.jar:na]
	at org.reflections.Reflections.scan(Reflections.java:204) [reflections-0.9.10.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:129) [reflections-0.9.10.jar:na]
	at com.canoo.dolphin.server.impl.ClasspathScanner.<init>(ClasspathScanner.java:75) [dolphin-platform-server-0.8.8.jar:0.8.8]
	at com.canoo.dolphin.server.bootstrap.DolphinPlatformBootstrap.start(DolphinPlatformBootstrap.java:84) [dolphin-platform-server-0.8.8.jar:0.8.8]
	aanoo.dolphin.server.spring.DolphinPlatformSpringBootstrap.onStartup(DolphinPlatformSpringBootstrap.java:51) [dolphin-platform-server-spring-0.8.8.jar:0.8.8]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:225) [spring-boot-1.3.2.RELEASE.jar:1.3.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:85) [spring-boot-1.3.2.RELEASE.jar:1.3.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:209) [spring-boot-1.3.2.RELEASE.jar:1.3.2.RELEASE]
	at org.springframework.boot.context.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:55) [spring-boot-1.3.2.RELEASE.jar:1.3.2.RELEASE]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5244) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
```

The stacktrace suggests that something went wrong with com.canoo.dolphin.server.impl.ClasspathScanner in line 75, but looking into it did not instantly reveal a hint wht the problem might be.

**Comment by hendrikebbers** [comment]
Can you send me the project?

**Comment by madmas** [comment]
Most easy: just generate a project with lazybones. I did not change any specifics.
https://github.com/canoo/dolphin-platform-lazybones-templates

**Comment by hendrikebbers** [comment]
Your project is under „Users/markus/tmp/lzbtmpl/nov15“, right?

**Comment by hendrikebbers** [comment]
Looks like the "PROJECT/server/build/resources/main" folder is not part of your project. This folder should be created by gradle. Even if I remove it by hand gradle will recreate the folder automatically in my test setup. The question is why this folder is missing in your project.

**Comment by hendrikebbers** [comment]
see https://github.com/ronmamo/reflections/issues/155
This is based on a gradle issue that behaves different on some systems. Maybe org.reflections can provide a better exception handling here.

**Comment by hendrikebbers** [comment]
Found a solution here: https://github.com/vojtechsoban/reflections/commit/60afd733d65f0f8f0f1fffd7521bdb010ac6b232
sadly the PR is still missing.
@madmas maybe this is a good issue for the Basel Hackergarten?

**Comment by madmas** [comment]
sure! :-) @hendrikebbers so you stop by some time soon?
