### ISSUE TITLE
:dolphin-remoting-shared:test FAILED

### ISSUE THREAD

**Issue by xeonn** [canoo/dolphin-platform#327]
Hi,

I am getting Assertion failed during compile

:dolphin-remoting-shared:test

```
org.opendolphin.core.comm.JsonCodecTest > testProperTypeEnAndDecoding FAILED
    Assertion failed: 

    assert in_command.oldValue == out_command.oldValue
           |          |        |  |           |
           |          |        |  |           Wed Mar 15 00:00:25 MYT 1905
           |          |        |  Command: ValueChanged attr:bla, Wed Mar 15 00:00:25 MYT 1905 -> Tue Jul 24 00:00:00 MYT 1906
           |          |        false
           |          Wed Mar 15 00:00:00 MYT 1905
           Command: ValueChanged attr:bla, Wed Mar 15 00:00:00 MYT 1905 -> Tue Jul 24 00:00:00 MYT 1906
        at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:402)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:650)
        at org.opendolphin.core.comm.JsonCodecTest.assertCorrectEnAndDecoding(JsonCodecTest.groovy:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
It is referring to this code [JsonCodecTest.groovy:116]
```
assertCorrectEnAndDecoding(new Date(0, 0, 1900), new Date(1, 1, 2000))
```
I believe it should be

```
assertCorrectEnAndDecoding(new Date(1900, 0, 0), new Date(2000, 1, 1))
```

**Comment by hendrikebbers** [comment]
Interesting since it's working on my local machine and on the travis build. Let me have a loom :)

**Comment by hendrikebbers** [comment]
Created a Pull Request (https://github.com/canoo/dolphin-platform/pull/328). Will merge it later
