### ISSUE TITLE
NPE while running generated project from SpringBoot archetype

### ISSUE THREAD

**Issue by kunsingh** [canoo/dolphin-platform#352]
`java.lang.NullPointerException: null
	at org.opendolphin.core.server.action.StoreValueChangeAction$1.handleCommand(StoreValueChangeAction.java:36) ~[dolphin-remoting-server-0.8.10.jar:0.8.10]
	at org.opendolphin.core.server.action.StoreValueChangeAction$1.handleCommand(StoreValueChangeAction.java:31) ~[dolphin-remoting-server-0.8.10.jar:0.8.10]
	at org.opendolphin.core.server.ServerConnector.receive(ServerConnector.java:61) ~[dolphin-remoting-server-0.8.10.jar:0.8.10]`

**Comment by kunsingh** [comment]
Duplicate of  #351. Closing.
