### ISSUE TITLE
Current release is not useable on old JBOSS web server

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#389]
Tried with JBOSS-EAP-6.4.0
Error-Log:
```
16:08:44,420 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-8) MSC000001: Failed to start service jboss.deployment.unit."todo-app.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."todo-app.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1936) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_101]
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408 Unsatisfied dependencies for type [ServletContext] with qualifiers [@Default] at injection point [[parameter 1] of [method] @Produces @ApplicationScoped public com.canoo.dolphin.server.javaee.CdiBeanFactory.createEventBus(ServletContext)]
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:315)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:284)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:147)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:167)
	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:386)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:371)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:379)
	at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:64)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1980) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1913) [jboss-msc-1.1.5.Final-redhat-1.jar:1.1.5.Final-redhat-1]
	... 3 more
```

**Comment by hendrikebbers** [comment]
We should do https://github.com/canoo/dolphin-platform/issues/429 first ;)

**Comment by hendrikebbers** [comment]
See http://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#additional_builtin_beans

**Comment by hendrikebbers** [comment]
Should be solved by providing DP modules.
