### ISSUE TITLE
NPE while publishing on Dolphin-EventBus without having a session

### ISSUE THREAD

**Issue by joha78** [canoo/dolphin-platform#534]
In 0.14.0 publishing was possible with no session. In 0.15.0 you get a NPE:

java.lang.NullPointerException: Argument 'clientSession' may not be null
	at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_121]
	at com.canoo.impl.platform.core.Assert.requireNonNull(Assert.java:45) ~[dolphin-platform-core-0.15.0.jar:0.15.0]
	at com.canoo.impl.server.context.DolphinContextCommunicationHandler.getContext(DolphinContextCommunicationHandler.java:112) ~[dolphin-platform-rpm-server-0.15.0.jar:0.15.0]
	at com.canoo.impl.server.context.DolphinContextCommunicationHandler.getCurrentDolphinContext(DolphinContextCommunicationHandler.java:127) ~[dolphin-platform-rpm-server-0.15.0.jar:0.15.0]
	at com.canoo.impl.server.RemotingModule$1.getCurrentDolphinContext(RemotingModule.java:83) ~[dolphin-platform-rpm-server-0.15.0.jar:0.15.0]
	at com.canoo.impl.server.event.AbstractEventBus.getCurrentContext(AbstractEventBus.java:214) ~[dolphin-platform-rpm-server-0.15.0.jar:0.15.0]
	at com.canoo.impl.server.event.AbstractEventBus.publishData(AbstractEventBus.java:173) ~[dolphin-platform-rpm-server-0.15.0.jar:0.15.0]
	at com.canoo.impl.server.event.AbstractEventBus.publish(AbstractEventBus.java:75) ~[dolphin-platform-rpm-server-0.15.0.jar:0.15.0]
	at com.canoo.impl.server.event.AbstractEventBus.publish(AbstractEventBus.java:69) ~[dolphin-platform-rpm-server-0.15.0.jar:0.15.0]
	at aero.sprouts.fly.service.EntityChangeNotificationService.publishCreation(EntityChangeNotificationService.java:105) ~[classes/:na]

**Comment by hendrikebbers** [comment]
Fixed and unit tests added
