### ISSUE TITLE
dolphin-platform-date-time-converter converting from LocalDate to tiny blob instead of date-time by design?

### ISSUE THREAD

**Issue by jermsam** [canoo/dolphin-platform#570]
![b6](https://user-images.githubusercontent.com/11094475/28283617-e5bbcc0c-6b36-11e7-9148-c398299b1666.JPG)
I've been trying to bind client side javaFx TableColumn<MyModel,LocalDate> column to a presentation model's Property<LocalDate>, this led me to defining LocalDate entity attributes to bind to the presentation Model on the server side controller. since DP 0.9.0 does not use Hibernate 5.1 (and later), I needed to define my own custom AttributeConverter<java.time.LocalDate, java.sql.Date> implementation.
When I did this without success, someone advised me to delete my own converter implementation and import dolphin-platform-date-time-converter.... when I did this: I first got the following error:
`Caused by: org.hibernate.type.SerializationException: could not deserialize
    at org.hibernate.internal.util.SerializationHelper.doDeserialize(SerializationHelper.java:262) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
    at org.hibernate.internal.util.SerializationHelper.deserialize(SerializationHelper.java:306) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]`

This suggested unusual database structure [remember that originally I had a data table in the database with datefields of data type datetime..... now it wasn't being serialized successfully with that of the new datastructure resulting from the imported date converter dependency. So I decided to delete my original table and restart the server. hmmmm....  see what I got for my new table:

**Comment by hendrikebbers** [comment]
Using Dolphin-platform-Date-Time-converter is right. The Dolphin Platform currently still Support Java 7. Since LocalDate is nee in Java 8 we Need to externalize the Converter in an optional Module.

**Comment by hendrikebbers** [comment]
I do not understand your hibernate issue. You can use the newest release of hibernate in combination with DP if you want

**Comment by hendrikebbers** [comment]
In addition I would update the Dolphin platform dependency to the newest release since a lot of bugs were fixed since 0.9

**Comment by jermsam** [comment]
I've been a little hesitant upgrading to 0.16.0 because of the many changes that where done [such as removal of the configuration class and @DolphinBean annotations. Tried to upgrade to it and I got so many bugs in my current code. for instance I had to change the import:
`import com.canoo.dolphin.server.spring.DolphinPlatformApplication;`
to
`import org.springframework.boot.web.support.SpringBootServletInitializer;`
and when I did so, I could not run the server.... I was getting a complaint of a missing Entity Manager.
However, if upgrading to 0.16.0 is the only option, I wouldn't mind taking that on. Hope it will fix that issue.

**Comment by hendrikebbers** [comment]
I do not think that upgrading DP will fix your issue. The issue looks like a hibernate problem and not like a DP problem. Can you post the complete stavktrave please?

**Comment by jermsam** [comment]
[b5.txt](https://github.com/canoo/dolphin-platform/files/1153661/b5.txt)

**Comment by hendrikebbers** [comment]
Ok, this looks like hibernate do not support a data type that you are using in your java db model class 
Maybe this is LocalDate? Maybe you need to update the hibernate version

**Comment by jermsam** [comment]
That means updating DP right? If so, what would you recommend as most stable latest release?

**Comment by hendrikebbers** [comment]
Wait a moment. I now seen your picture. In the DB you have a blob that stores the date. Mmh, think that is not the best choice. Modern DBs support Date datatypes. You should change this first, then load it as a java Date or LocalDate by using hibernate. Once this is working your problem should be fixed.
From my part of view this has nothing to do with DP. DP do not depend on hibernate and you can easily use any version of hibernate in combination with any version of DP

**Comment by jermsam** [comment]
The table in the picture was auto generated when I ran the server after adding the dependencies [I am doing JPA persistence in my spring boot. I am not manually drawing the DB tables. Before adding the dependencies, the auto generated table was having proper datetime type for the date fields.

**Comment by hendrikebbers** [comment]
Ah, ok
So you add spring-boot-data as a dependeny, right?
In that case you can exclude hibernate from that dependency and add a newer version

**Comment by hendrikebbers** [comment]
Or update DP ;)

**Comment by hendrikebbers** [comment]
How to exclude a transitive dependency depends on your build tool (maven or gradle) and you can find several examples online

**Comment by jermsam** [comment]
I want to try both alternatives. What would you recommend as the most stable latest release?

**Comment by hendrikebbers** [comment]
I think 0.16.1

**Comment by jermsam** [comment]
Ok. I let me include that one.
Which particular hibernate dependencies should I exclude?
core
entity-manager
hibernate-jpa

**Comment by jermsam** [comment]
or all

**Comment by hendrikebbers** [comment]
I am not a hibernate expert. I think you will find an answer online. Sorry

**Comment by jermsam** [comment]
ok. Thanks a lot boss. Let me first look into this. When it works I will bring back feedback [so as to benefit the entire community.

**Comment by ghostidentity** [comment]
Hi, the tinyblob datatype must be an issue from hibernate configuration.

DP does not support LocalDate as property, only java.util.Date.  Therefore you need initilize your model class similar below.

```
	private Property<java.util.Date> birthday;

	public Property<Date> getBirthday() {
		return birthday;
	}

	public void setBirthday(Property<Date> birthday) {
		this.birthday = birthday;
	}
```


And on the client side (javaFX)

	```
FXBinder.bind(birthday.valueProperty()).to(getModel().birthdayProperty(), DateConverter());

		birthday.setOnAction(event -> {

			Date date = Date.from(birthday.getValue().atStartOfDay(ZoneId.systemDefault()).toInstant());

			getModel().birthdayProperty().set(date);

		});

	private Converter<Date, LocalDate> DateConverter() {
		Converter<Date, LocalDate> c1 = new Converter<Date, LocalDate>() {

			@Override
			public LocalDate convert(Date value) {
				LocalDate date = value.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
				return date;
			}

		};
		return c1;
	}
```

**Comment by hendrikebbers** [comment]
@ghostidentity DP support LocalDate ;) But this is part of an optional module that needs to be added to client and server. Simply add "dolphin-platform-date-time-converter" as dependency and you can use all the new Java 8 date & time classes in the Dolphin Platform model

**Comment by ghostidentity** [comment]
Hi thanks! wasn't aware that there's optional module to include.

I tried the optional module along with dolphin-platform-server-javaee to test the localdate time in POM file.

But Wildfly complain that it cant find other dependencies.

```
WFLYCTL0184:    New missing/unsatisfied dependencies:
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".WeldBootstrapService (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.faces.webapp.FacetTag".WeldInstantiator, service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".WeldInstantiator, service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldTerminalListener".WeldInstantiator, service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".WeldInstantiator, WFLYCTL0208: ... and 3 more ] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".WeldStartService (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.faces.webapp.FacetTag".WeldInstantiator, service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".WeldInstantiator, service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldTerminalListener".WeldInstantiator, service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".CdiValidatorFactoryService, WFLYCTL0208: ... and 6 more ] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".beanmanager (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".CdiValidatorFactoryService] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".CREATE (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".START (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT"] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.faces.webapp.FacetTag".CREATE (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.faces.webapp.FacetTag".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.faces.webapp.FacetTag".START (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT"] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.faces.webapp.FacetTag".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.faces.webapp.FacetTag".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".CREATE (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT"] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".CREATE (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT"] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.ScriptFreeTLV".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".CREATE (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".START (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT"] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldTerminalListener".CREATE (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldTerminalListener".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldTerminalListener".START (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".deploymentCompleteService, service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT"] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldTerminalListener".WeldInstantiator (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldTerminalListener".START] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".ee.ComponentRegistry (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT".UndertowDeploymentInfoService] 
      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".jndiDependencyService (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."com.sun.faces.config.ConfigureListener".START, service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldTerminalListener".START, service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."org.jboss.weld.servlet.WeldInitialListener".START, service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".component."javax.servlet.jsp.jstl.tlv.PermittedTaglibsTLV".START, WFLYCTL0208: ... and 3 more ] 
      service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT" (missing) dependents: [service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".deploymentCompleteService] 
      service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT".UndertowDeploymentInfoService (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT"] 
      service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT".codec (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT".UndertowDeploymentInfoService] 
      service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT".session (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT".UndertowDeploymentInfoService] 
      service org.wildfly.request-controller.control-point."DolphinDemo-0.0.1-SNAPSHOT.war".undertow (missing) dependents: [service jboss.undertow.deployment.default-server.default-host."/DolphinDemo-0.0.1-SNAPSHOT".UndertowDeploymentInfoService] 
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."DolphinDemo-0.0.1-SNAPSHOT.war".WeldStartService
```

**Comment by hendrikebbers** [comment]
mmh, that must be another problem. the optional module has no relation to CDI, JSP or JSF. How have you added the dependency?

**Comment by ghostidentity** [comment]
Opps, nvm the issue. I added dolphin-platform-date-time-converter version 1.6 while the java ee module as  1.4. I correct the dependency version and now its working.

**Comment by hendrikebbers** [comment]
cool
