### ISSUE TITLE
Expose client dolphin internals

### ISSUE THREAD

**Issue by gemaSantiago** [canoo/dolphin-platform#58]
Currently on ICOS, during the login procedure an error may occur on the server side (athorization failure for example) that materializes on the client side as an uncaught exception(see below stacktrace)

`ClientConnector` has a generic mechanism to handle exceptions. This collaborator is exposed by `ClientDolphin`. But `ClientDolphin` is not reachable from `ClientBeanManager`.

```
org.apache.http.client.HttpResponseException: Unauthorized
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
    at org.opendolphin.core.client.comm.SessionAffinityCheckingResponseHandler.handleResponse(HttpClientConnector.groovy:109)
    at org.opendolphin.core.client.comm.SessionAffinityCheckingResponseHandler.handleResponse(HttpClientConnector.groovy)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1035)
    at org.apache.http.client.HttpClient$execute.call(Unknown Source)
    at org.opendolphin.core.client.comm.HttpClientConnector.transmit(HttpClientConnector.groovy:81)
    at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:368)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
    at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2_closure10.doCall(ClientConnector.groovy:76)
    at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2_closurell(ClientConnector.groovy)
    at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:417)
    at groovy.lang.Closure.run(Closure.java:504)
    at org.opendolphin.core.client.comm.ClientConnector.doExceptionSafe(ClientConnector.groovy:145)
    at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:368)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
    at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2.doCall(ClientConnector.groovy:78)
    at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaCva:278)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
    at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
    at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
    at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
    at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
    at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
    at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[2015-09-15 15:55:27,225] [JavaFX Application Thread] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception
java.security.PrivilegedActionException: org.apache.http.client.HttpResponseException: Unauthorized
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: org.apache.http.client.HttpResponseException: Unauthorized
    at org.opendolphin.core.client.comm.SessionAffinityCheckingResponseHandler.handleResponse(HttpClientConnector.groovy:109)
    at org.opendolphin.core.client.comm.SessionAffinityCheckingResponseHandler.handleResponse(HttpClientConnector.groovy)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1035)
    at org.apache.http.client.HttpClient$execute.call(Unknown Source)
    at org.opendolphin.core.client.comm.HttpClientConnector.transmit(HttpClientConnector.groovy:81)
    at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2_closure10.doCall(ClientConnector.groovy:76)
    at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2_closure10.doCall(ClientConnector.groovy)
    at org.opendolphin.core.client.comm.ClientConnector.doExceptionSafe(ClientConnector.groovy:145)
    at org.opendolphin.core.client.comm.ClientConnector$_startCommandProcessing_closure2.doCall(ClientConnector.groovy:78)
    at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
    at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
    at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
    at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
    at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
    at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
    at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
```

**Comment by netopyr** [comment]
Is this still needed when we have proper error handling?

**Comment by aalmiray** [comment]
Perhaps not. OD's error handling mechanism is a global one. I think DP has to offer failure/error handling at different levels

 - when a property value changes and the server reacts to it (https://github.com/canoo/dolphin-platform/issues/65)
 - when a semantic failure occurs (https://github.com/canoo/dolphin-platform/issues/49)
 - when a plumbing errors occurs (network goes down for example, unexpected NPE server side) (https://github.com/canoo/dolphin-platform/issues/49)
 - the global one might be needed depending if server push is enabled I guess
