### ISSUE TITLE
RuntimeException in a change listener on the server ends in wrong values

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#65]
As seen at a Dolphin Platform training:
- A change listener is added to a property on the server and the value is changed on the client
- A RuntimeException is thrown in the change listener on the server
- Based on this some value won't update by future changes.

Concerete example: We had a calculator with 2 input properties (String) and a result property (String). Change listeners were added to the value properties that calc the result based on the input. Here a NPE is thrown since the values had a default value of "null" (NPE by Double.parseString(null)). In addition we had a reset action in the controller that sets the input values to "0". By doing so (after the exception was thrown in an earlier server roundtrip) only one input value is updated to "0" on the client.

**Comment by pb00067** [comment]
```
package it.wuerthphoenix.controller;

import com.canoo.dolphin.server.DolphinAction;
import com.canoo.dolphin.server.DolphinController;
import com.canoo.dolphin.server.DolphinModel;
import it.wuerthphoenix.Constants;
import it.wuerthphoenix.model.CalculatorModel;
import it.wuerthphoenix.model.MyModel;

import javax.annotation.PostConstruct;

/**
 * This class defines the controller. Whenever a matching view is created in a client a controller instance will be
 * created on the server. The controller is completelly managed by the container and therefore features like CDI can
 * be used without any problems in the controller.
 * The {@link DolphinController} annotation defines the unique name of this controller type. In this sample a static
 * constant is used for the name that is shared with the JavaFX client.
 */
@DolphinController(Constants.CALCULATOR_CONTROLLER_NAME)
public class CalculatorController {

    /**
     * Defines the model of the MVC group. Like the controller this model will automatically be managed by the container
     * and before the init() method (annotated with {@link PostConstruct}) is called the model will be injected in the
     * controller.
     */
    @DolphinModel
    private CalculatorModel model;

    /**
     * Like in any managed bean this method will be called once the initalisation of the instance (injection etc.) is done.
     */
    @PostConstruct
    public void init() {
        // An observer is added to the value property of the model. Since the model will automatically be synchronized
        // between client and server the observer will be called whenever the model changes on the client. When having
        // a look a the client implementation you will see that the value property is bound to an input field. By doing
        // so the observer that is defined here will automatically be called when the user types text in the input on the client
        model.summand1Property().onChanged(e -> calcResult());
        model.summand2Property().onChanged(e -> calcResult());
    }
    
    private void calcResult() {
    	try {
	    	double sum1 = Double.parseDouble(model.getSummand1Value());
	    	double sum2 = Double.parseDouble(model.getSummand2Value());
	    	model.setResultValue("" + (sum1 + sum2)); 
    	}
    	catch (NumberFormatException nf) {
    		model.setResultValue("NumberFormatException"); 
    	}
//    	catch (Exception e) {
//    		//System.err.println("here we aere");
//    	}
    }

    /**
     * By adding the {@link DolphinAction} annotation to a method this method can be triggered as a controller action on
     * the client. To do so the client must trigger the action based on its name. As long as no value is defined for the
     * annotation the method name will be used. This means that this method can be triggered by calling a "reset" action
     * on the client.
     */
    @DolphinAction(Constants.RESET_ACTION)
    public void reset() {
    	model.setSummand1("0");
    	model.setSummand2("0");
        //model.setResultValue("0");
    }
}
```

**Comment by pb00067** [comment]
2016-01-27 09:04:42.998 ERROR 20364 --- [nio-8080-exec-6] a.c.c.C.[.[.[.[dolphin-platform-servlet] : Servlet.service() for servlet [dolphin-platform-servlet] in context with path [] threw exception

java.lang.RuntimeException: Error in Dolphin command handling
	at com.canoo.dolphin.server.context.DolphinContextHandler.handle(DolphinContextHandler.java:86)
	at com.canoo.dolphin.server.servlet.DolphinPlatformServlet.doPost(DolphinPlatformServlet.java:34)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.canoo.dolphin.server.servlet.CrossSiteOriginFilter.doFilter(CrossSiteOriginFilter.java:42)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at it.wuerthphoenix.controller.CalculatorController.calcResult(CalculatorController.java:46)
	at it.wuerthphoenix.controller.CalculatorController.lambda$0(CalculatorController.java:39)
	at com.canoo.dolphin.impl.PropertyImpl.firePropertyChanged(PropertyImpl.java:97)
	at com.canoo.dolphin.impl.PropertyImpl$1.propertyChange(PropertyImpl.java:52)
	at org.opendolphin.core.AbstractObservable.firePropertyChange(AbstractObservable.java:58)
	at org.opendolphin.core.BaseAttribute.setValue(BaseAttribute.java:124)
	at org.opendolphin.core.server.ServerAttribute.super$3$setValue(ServerAttribute.groovy)
	at org.opendolphin.core.server.ServerAttribute.setValue(ServerAttribute.groovy:47)
	at org.opendolphin.core.server.ServerAttribute.setProperty(ServerAttribute.groovy)
	at org.opendolphin.core.server.action.StoreValueChangeAction$_registerIn_closure1_closure2.doCall(StoreValueChangeAction.groovy:36)
	at org.opendolphin.core.server.action.StoreValueChangeAction$_registerIn_closure1_closure2.doCall(StoreValueChangeAction.groovy)
	at org.opendolphin.core.server.ServerAttribute.silently(ServerAttribute.groovy:97)
	at org.opendolphin.core.server.ServerAttribute$silently.call(Unknown Source)
	at org.opendolphin.core.server.action.StoreValueChangeAction$_registerIn_closure1.doCall(StoreValueChangeAction.groovy:35)
	at org.opendolphin.core.server.comm.CommandHandlerClosureAdapter.handleCommand(CommandHandlerClosureAdapter.java:37)
	at org.opendolphin.core.server.comm.CommandHandler$handleCommand.call(Unknown Source)
	at org.opendolphin.core.server.ServerConnector.receive(ServerConnector.groovy:65)
	at com.canoo.dolphin.server.context.DolphinContext.handleRequest(DolphinContext.java:270)
	at com.canoo.dolphin.server.context.DolphinContextHandler.handle(DolphinContextHandler.java:84)
	at com.canoo.dolphin.server.servlet.DolphinPlatformServlet.doPost(DolphinPlatformServlet.java:34)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.canoo.dolphin.server.servlet.CrossSiteOriginFilter.doFilter(CrossSiteOriginFilter.java:42)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

**Comment by hendrikebbers** [comment]
@kunsingh We should check if this error still happens

**Comment by kunsingh** [comment]
It's working fine if we take care of initial null value of model.

`
@DolphinController(CALC_CONTROLLER_NAME)
public class CalcController {


    @DolphinModel
    private Calc model;

    @PostConstruct
    public void init() {
        model.getInput1Property().onChanged(e -> calcResult());
        model.getInput2Property().onChanged(e -> calcResult());
    }

    private void calcResult() {
        try {
            double sum1 = model.getInput1().get() != null?Double.parseDouble(model.getInput1().get()):0;
            double sum2 = model.getInput2().get() != null?Double.parseDouble(model.getInput2().get()):0;
            model.getResult().set("" + (sum1 + sum2));
        }
        catch (NumberFormatException nf) {
            model.getResult().set("NumberFormatException");
        }
      catch (Exception e) {
          e.printStackTrace();
      }
    }

    @DolphinAction(RESET_ACTION)
    public void reset() {
        model.getInput1().set("0");
        model.getInput2().set("0");
    }
}


`

**Comment by hendrikebbers** [comment]
That is right :) But I would prefer to have a remoting exception (if you do not take care) instead of having a wrong value in the property. I think it's better if such a case destroys the connection / context if you do not handle the error instead of having wrong values on the server.

**Comment by hendrikebbers** [comment]
Here is an example how a manual test might look like:

```
@DolphinController(CALC_CONTROLLER_NAME)
public class CalcController {

    @DolphinModel
    private Calc model;

    @PostConstruct
    public void init() {
        model.getInput1Property().onChanged(e -> calc1());
        model.getInput2Property().onChanged(e -> calc2());
    }

    private void calc1() {
        throws new RuntimeException("ARGH!");
    }

    private void calc2() {
        System.out.println("1: " + model.getInput1());
        System.out.println("2: " + model.getInput2());
    }

}
```

**Comment by kunsingh** [comment]
Validated - Server side model data is consistent despite of RunTimeException in onChange.
