### ISSUE TITLE
Destroying a Controller results in an IllegalArgumentException

### ISSUE THREAD

**Issue by moschkom** [canoo/dolphin-platform#66]
From time to time I see an IllegalArgumentException on the server. I can not tell under which circumstances the problem occurs, because it is not failing every time when we call **controllerProxy.destroy()** on the client side. 

    [2016-01-29 16:58:51.475] boot - 13548 ERROR [http-nio-8080-exec-3] --- ServerConnector: S: an error ocurred while processing Command: dolphin_platform_intern_destroyController
    java.lang.IllegalArgumentException: instance must not be null!
        at com.canoo.dolphin.server.spring.SpringContainerManager.destroyController(SpringContainerManager.java:64)
        at com.canoo.dolphin.server.controller.ControllerHandler.destroyController(ControllerHandler.java:129)
        at com.canoo.dolphin.server.context.DolphinContext.onDestroyController(DolphinContext.java:202)
        at com.canoo.dolphin.server.context.DolphinContext.access$100(DolphinContext.java:60)
        at com.canoo.dolphin.server.context.DolphinContext$1$2.handleCommand(DolphinContext.java:136)
        at org.opendolphin.core.server.comm.CommandHandler$handleCommand.call(Unknown Source)
        at org.opendolphin.core.server.ServerConnector.receive(ServerConnector.groovy:65)
        at com.canoo.dolphin.server.context.DolphinContext.handleRequest(DolphinContext.java:270)
        at com.canoo.dolphin.server.context.DolphinContextHandler.handle(DolphinContextHandler.java:84)
        at com.canoo.dolphin.server.servlet.DolphinPlatformServlet.doPost(DolphinPlatformServlet.java:34)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.canoo.dolphin.server.servlet.CrossSiteOriginFilter.doFilter(CrossSiteOriginFilter.java:42)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:295)
        at ... 
    [2016-01-29 16:58:51.476] boot - 13548 ERROR [http-nio-8080-exec-3] --- [dolphin-platform-servlet]: Servlet.service() for servlet [dolphin-platform-servlet] in context with path [] threw exception
    java.lang.RuntimeException: Error in Dolphin command handling
        at com.canoo.dolphin.server.context.DolphinContextHandler.handle(DolphinContextHandler.java:86)
        at com.canoo.dolphin.server.servlet.DolphinPlatformServlet.doPost(DolphinPlatformServlet.java:34)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.canoo.dolphin.server.servlet.CrossSiteOriginFilter.doFilter(CrossSiteOriginFilter.java:42)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:295)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at ... 
    Caused by: java.lang.IllegalArgumentException: instance must not be null!
        at com.canoo.dolphin.server.spring.SpringContainerManager.destroyController(SpringContainerManager.java:64)
        at com.canoo.dolphin.server.controller.ControllerHandler.destroyController(ControllerHandler.java:129)
        at com.canoo.dolphin.server.context.DolphinContext.onDestroyController(DolphinContext.java:202)
        at com.canoo.dolphin.server.context.DolphinContext.access$100(DolphinContext.java:60)
        at com.canoo.dolphin.server.context.DolphinContext$1$2.handleCommand(DolphinContext.java:136)
        at org.opendolphin.core.server.comm.CommandHandler$handleCommand.call(Unknown Source)
        at org.opendolphin.core.server.ServerConnector.receive(ServerConnector.groovy:65)
        at com.canoo.dolphin.server.context.DolphinContext.handleRequest(DolphinContext.java:270)
        at com.canoo.dolphin.server.context.DolphinContextHandler.handle(DolphinContextHandler.java:84)
        at com.canoo.dolphin.server.servlet.DolphinPlatformServlet.doPost(DolphinPlatformServlet.java:34)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.canoo.dolphin.server.servlet.CrossSiteOriginFilter.doFilter(CrossSiteOriginFilter.java:42)
        at ...

**Comment by hendrikebbers** [comment]
Looks like the controller instance on the server is already null. Can you check if you maybe call it several times for the same controller instance. Otherwise it looks like a bug in the controller handling in the server.

**Comment by moschkom** [comment]
I don't think that we destroy the same controller more than once. I will try to identify a pattern when the exception happens (if there is a pattern).

**Comment by hendrikebbers** [comment]
@moschkom @aalmiray Is this still open or maybe a duplicate?

**Comment by hendrikebbers** [comment]
Maybe this will be resolved with #131 ?? We need to check it after the merge.
