### ISSUE TITLE
Null Pointer Exceptions

### ISSUE THREAD

**Issue by Jarota** [canoo/dolphin-platform#685]
See this PullRequest:  #666 

There's a number of null pointer exceptions when building ( `./gradlew clean build` )
I've attached a file with the build output, containing the exceptions.
[buildOutput.txt](https://github.com/canoo/dolphin-platform/files/1398529/buildOutput.txt)

**Comment by hendrikebbers** [comment]
The interesting part of the log is this one:

 2017-10-19 06:11:11.395  WARN 5294 --- [    Test worker] org.reflections.Reflections              : could not create Vfs.Dir from url. ignoring the exception and continuing

   ``` org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/home/jammygit/code/dolphin-platform/platform-integration-tests/integration-server/build/resources/test]
    either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
    	at org.reflections.vfs.Vfs.fromURL(Vfs.java:109) ~[reflections-0.9.10.jar:na]
    	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91) ~[reflections-0.9.10.jar:na]
    	at org.reflections.Reflections.scan(Reflections.java:237) [reflections-0.9.10.jar:na]
    	at org.reflections.Reflections.scan(Reflections.java:204) [reflections-0.9.10.jar:na]
    	at org.reflections.Reflections.<init>(Reflections.java:129) [reflections-0.9.10.jar:na]
    	at com.canoo.dp.impl.server.scanner.DefaultClasspathScanner.<init>(DefaultClasspathScanner.java:76) [dolphin-platform-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
    	at com.canoo.dp.impl.server.scanner.DefaultClasspathScanner.<init>(DefaultClasspathScanner.java:43) [dolphin-platform-server-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
    	at com.canoo.impl.dp.spring.test.TestConfiguration.<init>(TestConfiguration.java:74) [dolphin-platform-spring-controller-tester-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
    	at com.canoo.impl.dp.spring.test.DolphinPlatformSpringTestBootstrap.createTestConfiguration(DolphinPlatformSpringTestBootstrap.java:52) [dolphin-platform-spring-controller-tester-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
    	at com.canoo.impl.dp.spring.test.DolphinPlatformSpringTestBootstrap$$EnhancerBySpringCGLIB$$c15ec7c7.CGLIB$createTestConfiguration$0(<generated>) [dolphin-platform-spring-controller-tester-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
    	at com.canoo.impl.dp.spring.test.DolphinPlatformSpringTestBootstrap$$EnhancerBySpringCGLIB$$c15ec7c7$$FastClassBySpringCGLIB$$b7cd71a7.invoke(<generated>) [dolphin-platform-spring-controller-tester-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
```

It looks like this is related to an issue of the reflections lib. Anyway we should try to handle this one better.

**Comment by hendrikebbers** [comment]
See related issue for reflections library https://github.com/ronmamo/reflections/issues/204

**Comment by mohamadLy** [comment]
I can take this, if it's alright with you.

**Comment by Jarota** [comment]
Absolutely, work away! :)

**Comment by mohamadLy** [comment]
@Jarota thanks for the opportunity
