### ISSUE TITLE
JS project can not be build anymore

### ISSUE THREAD

**Issue by hendrikebbers** [canoo/dolphin-platform#789]
Calling `gulp clean verify build` ends with an error:

```
20 12 2017 15:27:20.569:ERROR [launcher]: { Error: spawn ENOTDIR
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
...
```

Here is the complete shell protocol:

```
Hendriks-MacBook-Pro-2:dolphin-platform-js hendrikebbers$ npm install

> wd@1.4.0 install /Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma-sauce-launcher/node_modules/wd
> node scripts/build-browser-scripts


> sauce-connect-launcher@0.17.0 postinstall /Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma-sauce-launcher/node_modules/sauce-connect-launcher
> node scripts/install.js || nodejs scripts/install.js

added 278 packages, removed 1299 packages and updated 8 packages in 43.636s
Hendriks-MacBook-Pro-2:dolphin-platform-js hendrikebbers$ bower install
Hendriks-MacBook-Pro-2:dolphin-platform-js hendrikebbers$ npm update
+ tsify@3.0.4
+ typescript@2.6.2
removed 133 packages and updated 2 packages in 18.619s


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.3.0 → 5.6.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯

Hendriks-MacBook-Pro-2:dolphin-platform-js hendrikebbers$ bower update
bower core.js#2.4.x             cached https://github.com/zloirock/core-js.git#2.4.1
bower core.js#2.4.x           validate 2.4.1 against https://github.com/zloirock/core-js.git#2.4.x


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 1.7.9 → 1.8.2    │
   │   Run npm i -g bower to update      │
   │                                     │
   ╰─────────────────────────────────────╯

Hendriks-MacBook-Pro-2:dolphin-platform-js hendrikebbers$ gulp clean verify build
[15:27:09] Using gulpfile ~/git/dolphin-platform-js/gulpfile.js
[15:27:09] Starting 'clean'...
[15:27:09] Finished 'clean' after 7.53 ms
[15:27:09] Starting 'lint'...
[15:27:10] Starting 'build_impl'...
[15:27:15] Finished 'lint' after 5.77 s
[15:27:17] Finished 'build_impl' after 7.06 s
[15:27:17] Starting 'build-test'...
[15:27:19] Finished 'build-test' after 2.63 s
[15:27:19] Starting 'test'...
20 12 2017 15:27:20.553:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
20 12 2017 15:27:20.559:INFO [launcher]: Starting browser PhantomJS
20 12 2017 15:27:20.569:ERROR [launcher]: { Error: spawn ENOTDIR
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.ProcessLauncher._execCommand (/Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma/lib/launchers/process.js:63:21)
    at Object.PhantomJSBrowser._start (/Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma-phantomjs-launcher/index.js:80:10)
    at Object.<anonymous> (/Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma/lib/launchers/process.js:14:10)
    at emitOne (events.js:120:20)
    at Object.emit (events.js:210:7)
    at Object.BaseLauncher.start (/Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma/lib/launchers/base.js:42:10)
    at /Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma/lib/launcher.js:94:17
    at next (/Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma/node_modules/batch/index.js:118:7)
    at Batch.end (/Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma/node_modules/batch/index.js:154:5)
    at Launcher.launch (/Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma/lib/launcher.js:111:11)
    at Injector.invoke (/Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Server.<anonymous> (/Users/hendrikebbers/git/dolphin-platform-js/node_modules/karma/lib/server.js:171:24)
    at Object.onceWrapper (events.js:314:30) code: 'ENOTDIR', errno: 'ENOTDIR', syscall: 'spawn' }

```

**Comment by hendrikebbers** [comment]
@kunsingh @hastebrot  NEED HELP :)

**Comment by kunsingh** [comment]
Its working fine on my machine. Machine dependent.
